name: pybpod-environment
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cycler=0.10.0=py35hcc71164_0
  - git=2.15.0=heaa8ca2_0
  - icc_rt=2017.0.4=h97af966_0
  - intel-openmp=2018.0.0=hcd89f80_7
  - mkl=2018.0.0=h36b65af_4
  - numpy=1.13.3=py35hb7e80fb_0
  - openssl=1.0.2l=vc14_0
  - pip=9.0.1=py35h691316f_4
  - pyparsing=2.2.0=py35hcabcaab_1
  - pyqt=5.6.0=py35hd46907b_5
  - pyserial=3.4=py35he0af20a_0
  - python=3.5.4=h1357f44_23
  - python-dateutil=2.6.1=py35h6b299a3_1
  - pytz=2017.2=py35h3d6be01_1
  - setuptools=36.5.0=py35h21a22e4_0
  - sip=4.18.1=py35h01cbaa7_2
  - six=1.11.0=py35hc1da2df_1
  - tornado=4.5.2=py35h03246f3_0
  - vc=14=h2379b0c_2
  - vs2015_runtime=14.0.25123=hd4c4e62_2
  - wheel=0.29.0=py35hdbcb6e6_1
  - wincertstore=0.2=py35hfebbdb8_0
  - zlib=1.2.11=vc14_0
  - backports=1.0=py35_1
  - backports.functools_lru_cache=1.4=py35_1
  - freetype=2.7=vc14_2
  - icu=58.2=vc14_0
  - jpeg=9b=vc14_2
  - libpng=1.6.28=vc14_2
  - matplotlib=2.1.0=py35_1
  - qscintilla2=2.9.3=py35_vc14_2
  - qt=5.6.2=vc14_1
  - sqlite=3.19.3=vc14_1
  - ca-certificates=2017.08.26=h94faf87_0
  - certifi=2017.7.27.1=py35hbab57cd_0
  - pandas=0.22.0=py35h6538335_0
  - scipy=1.0.0=py35h75710e8_0
  - pip:
    - cffi==1.11.5
    - pycparser==2.18
    - python-osc==1.6.6
    - sounddevice==0.3.11
prefix: pybpod-environment
