name: pybpod-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - qscintilla2=2.9.3=py36_2
  - ca-certificates=2017.08.26=h1d4fec5_0
  - certifi=2017.11.5=py36hf29ccca_0
  - curl=7.55.1=h78862de_4
  - cycler=0.10.0=py36h93f1223_0
  - dbus=1.10.22=h3b5a359_0
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.4=h88586e7_1
  - freetype=2.8=hab7d2ae_1
  - git=2.15.0=pl526h838b92b_0
  - glib=2.53.6=h5d9569c_2
  - gst-plugins-base=1.12.2=he3457e5_0
  - gstreamer=1.12.2=h4f93127_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2018.0.0=hc7b2577_8
  - jpeg=9b=h024ee3a_2
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.32=hbd3595f_4
  - libssh2=1.8.0=h2d05a93_3
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - libxcb=1.12=hcd93eb1_4
  - libxml2=2.9.4=h2e8b1d7_6
  - matplotlib=2.1.0=py36hba5de38_0
  - mkl=2018.0.1=h19d6760_4
  - ncurses=6.0=h9df7e31_2
  - numpy=1.13.3=py36ha12f23b_0
  - openssl=1.0.2m=h26d622b_1
  - pandas=0.22.0=py36hf484d3e_0
  - pcre=8.41=hc27e229_1
  - perl=5.26.0=hae598fd_0
  - pip=9.0.1=py36h6c6f9ce_4
  - pyparsing=2.2.0=py36hee85983_1
  - pyqt=5.6.0=py36h0386399_5
  - pyserial=3.4=py36h08da44b_0
  - python=3.6.3=h6c0c0dc_5
  - python-dateutil=2.6.1=py36h88d3b88_1
  - pytz=2017.3=py36h63b9c63_0
  - qt=5.6.2=h974d657_12
  - readline=7.0=ha6073c6_4
  - scipy=1.0.0=py36hbf646e7_0
  - setuptools=36.5.0=py36he42e2e1_0
  - sip=4.18.1=py36h51ed4ed_2
  - six=1.11.0=py36h372c433_1
  - sqlite=3.20.1=hb898158_2
  - tk=8.6.7=hc745277_3
  - tornado=4.5.2=py36h1283b2a_0
  - wheel=0.30.0=py36hfd4bba0_1
  - xz=5.2.3=h55aa19d_2
  - zlib=1.2.11=ha838bed_2
  - pip:
    - anyqt==0.0.8
    - cffi==1.11.5
    - pycparser==2.18
    - python-osc==1.6.6
    - send2trash==1.4.2
    - sounddevice==0.3.11
prefix: /home/nico/miniconda3/envs/pybpod-environment

