# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [develop, rc]
  pull_request:
    branches: [develop, rc]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  incubator:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: ["ubuntu-latest", "windows-latest"] # "macos-latest",
        python-version: ["3.7"]
    steps:
      - name: Clone iblrig repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: iblrig
          environment-file: environment.yaml
      - name: Commands
        shell: bash -l {0}
        run: |
          conda activate base
          python -V
          which pip
          pip install setuptools wheel packaging
          python install.py --reinstall-response y --config-response y --bonsai-response y --ONE-response n
          conda activate iblrig
          python -c "from one.api import ONE; ONE(base_url='https://test.alyx.internationalbrainlab.org', username='test_user', password='TapetesBloc18', silent=True)"
          python -m unittest discover
